### ISSUE TITLE
Maestro Router ABI decompilation failed

### ISSUE THREAD

**Issue by shouc** [fuzzland/ityfuzz#277]
Too many unknown function signature for "0x80a64c6d7f12c47b7c66c5b4e20e72bc1fcd5d9e", we are going to decompile this contract using Heimdall

timeout 5m ./target/release/ityfuzz evm -o -t 0x80a64c6D7f12C47B7c66c5B4E20E72bc1FCd5d9e -c eth --onchain-block-number 0 -f -i -p

**Comment by 0xAWM** [comment]
This issue is due to ityfuzz not being able to get any usable ABI.

Heimdall:
error: failed to resolve any function selectors from 0x80a64c6D7f12C47B7c66c5B4E20E72bc1FCd5d9e

And I checked the runtimecode:

0x60806040526001600160a01b03337f000000000000000000000000e8ac39f0a15dc7eb9cf32c7639e633f24f9ec9ab82160361006a575f356001600160e01b03191663278f794360e11b14610060576040516334ad5dbb60e21b8152600490fd5b610068610106565b005b7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc54165f808092368280378136915af43d82803e156100a7573d90f35b3d90fd5b634e487b7160e01b5f52604160045260245ffd5b6040519190601f01601f1916820167ffffffffffffffff8111838210176100e557604052565b6100ab565b67ffffffffffffffff81116100e557601f01601f191660200190565b3660041161018f57604036600319011261018f576004356001600160a01b0381169081900361018f576024359067ffffffffffffffff821161018f573660238301121561018f5781600401359061016461015f836100ea565b6100bf565b91808352366024828601011161018f576020815f92602461018d97018387013784010152610193565b565b5f80fd5b90813b1561022a577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc80546001600160a01b0319166001600160a01b0384169081179091557fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b5f80a280511561020f5761020c9161024b565b50565b50503461021857565b60405163b398979f60e01b8152600490fd5b604051634c9c8ce360e01b81526001600160a01b0383166004820152602490fd5b5f8061027d93602081519101845af43d15610280573d9161026e61015f846100ea565b9283523d5f602085013e610284565b90565b6060915b906102ab575080511561029957805190602001fd5b604051630a12f52160e11b8152600490fd5b815115806102de575b6102bc575090565b604051639996b31560e01b81526001600160a01b039091166004820152602490fd5b50803b156102b456fea264697066735822122030cc9d72e095e794d8286b088776326d90cf6b4d62a84a41c9928eb1eb96b3d064736f6c63430008150033

There is no selector in it at all.

For ref:
<img width="1319" alt="image" src="https://github.com/fuzzland/ityfuzz/assets/29773064/bbc96f04-fe7a-4f0d-b3ec-e198da50ad3b">


This contract may be constructed by Yul/Huff/Bytecode.

**Comment by 0xAWM** [comment]
Closed because only solc  generated bytecode is supported
